/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class AmbientNoiseBuilder {
    //the instance to build
    private AmbientNoise ambientNoise;

    /**
     * Default constructor to initialize the instance
     */
    public AmbientNoiseBuilder() {
        ambientNoise = new AmbientNoise();
    }

    public AmbientNoiseBuilder value(double value) {
        ambientNoise.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AmbientNoise build() {
        return ambientNoise;
    }
}