/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AmbientNoise type.
 */
public class AmbientNoise {
    private double value;

    /**
     * Default constructor.
     */
    public AmbientNoise() {
    }

    /**
     * Initialization constructor.
     * @param  value  double value for value.
     */
    public AmbientNoise(
            double value) {
        this.value = value;
    }

    /**
     * Getter for Value.
     * @return Returns the double
     */
    @JsonGetter("value")
    public double getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for double
     */
    @JsonSetter("value")
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Converts this AmbientNoise into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AmbientNoise [" + "value=" + value + "]";
    }

    /**
     * Builds a new {@link AmbientNoise.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AmbientNoise.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value);
        return builder;
    }

    /**
     * Class to build instances of {@link AmbientNoise}.
     */
    public static class Builder {
        private double value;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  double value for value.
         */
        public Builder(double value) {
            this.value = value;
        }

        /**
         * Setter for value.
         * @param  value  double value for value.
         * @return Builder
         */
        public Builder value(double value) {
            this.value = value;
            return this;
        }

        /**
         * Builds a new {@link AmbientNoise} object using the set fields.
         * @return {@link AmbientNoise}
         */
        public AmbientNoise build() {
            return new AmbientNoise(value);
        }
    }
}
