/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Attrs1 type.
 */
public class Attrs1 {
    private Pressure pressure;
    private Humidity4 humidity;
    private Temperature7 temperature;

    /**
     * Default constructor.
     */
    public Attrs1() {
    }

    /**
     * Initialization constructor.
     * @param  pressure  Pressure value for pressure.
     * @param  humidity  Humidity4 value for humidity.
     * @param  temperature  Temperature7 value for temperature.
     */
    public Attrs1(
            Pressure pressure,
            Humidity4 humidity,
            Temperature7 temperature) {
        this.pressure = pressure;
        this.humidity = humidity;
        this.temperature = temperature;
    }

    /**
     * Getter for Pressure.
     * @return Returns the Pressure
     */
    @JsonGetter("pressure")
    public Pressure getPressure() {
        return pressure;
    }

    /**
     * Setter for Pressure.
     * @param pressure Value for Pressure
     */
    @JsonSetter("pressure")
    public void setPressure(Pressure pressure) {
        this.pressure = pressure;
    }

    /**
     * Getter for Humidity.
     * @return Returns the Humidity4
     */
    @JsonGetter("humidity")
    public Humidity4 getHumidity() {
        return humidity;
    }

    /**
     * Setter for Humidity.
     * @param humidity Value for Humidity4
     */
    @JsonSetter("humidity")
    public void setHumidity(Humidity4 humidity) {
        this.humidity = humidity;
    }

    /**
     * Getter for Temperature.
     * @return Returns the Temperature7
     */
    @JsonGetter("temperature")
    public Temperature7 getTemperature() {
        return temperature;
    }

    /**
     * Setter for Temperature.
     * @param temperature Value for Temperature7
     */
    @JsonSetter("temperature")
    public void setTemperature(Temperature7 temperature) {
        this.temperature = temperature;
    }

    /**
     * Converts this Attrs1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Attrs1 [" + "pressure=" + pressure + ", humidity=" + humidity + ", temperature="
                + temperature + "]";
    }

    /**
     * Builds a new {@link Attrs1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Attrs1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(pressure, humidity, temperature);
        return builder;
    }

    /**
     * Class to build instances of {@link Attrs1}.
     */
    public static class Builder {
        private Pressure pressure;
        private Humidity4 humidity;
        private Temperature7 temperature;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  pressure  Pressure value for pressure.
         * @param  humidity  Humidity4 value for humidity.
         * @param  temperature  Temperature7 value for temperature.
         */
        public Builder(Pressure pressure, Humidity4 humidity, Temperature7 temperature) {
            this.pressure = pressure;
            this.humidity = humidity;
            this.temperature = temperature;
        }

        /**
         * Setter for pressure.
         * @param  pressure  Pressure value for pressure.
         * @return Builder
         */
        public Builder pressure(Pressure pressure) {
            this.pressure = pressure;
            return this;
        }

        /**
         * Setter for humidity.
         * @param  humidity  Humidity4 value for humidity.
         * @return Builder
         */
        public Builder humidity(Humidity4 humidity) {
            this.humidity = humidity;
            return this;
        }

        /**
         * Setter for temperature.
         * @param  temperature  Temperature7 value for temperature.
         * @return Builder
         */
        public Builder temperature(Temperature7 temperature) {
            this.temperature = temperature;
            return this;
        }

        /**
         * Builds a new {@link Attrs1} object using the set fields.
         * @return {@link Attrs1}
         */
        public Attrs1 build() {
            return new Attrs1(pressure, humidity, temperature);
        }
    }
}
