/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class CreateSubscriptionRequestBuilder {
    //the instance to build
    private CreateSubscriptionRequest createSubscriptionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateSubscriptionRequestBuilder() {
        createSubscriptionRequest = new CreateSubscriptionRequest();
    }

    public CreateSubscriptionRequestBuilder description(String description) {
        createSubscriptionRequest.setDescription(description);
        return this;
    }

    public CreateSubscriptionRequestBuilder subject(Subject1 subject) {
        createSubscriptionRequest.setSubject(subject);
        return this;
    }

    public CreateSubscriptionRequestBuilder notification(Notification1 notification) {
        createSubscriptionRequest.setNotification(notification);
        return this;
    }

    public CreateSubscriptionRequestBuilder expires(String expires) {
        createSubscriptionRequest.setExpires(expires);
        return this;
    }

    public CreateSubscriptionRequestBuilder throttling(int throttling) {
        createSubscriptionRequest.setThrottling(throttling);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateSubscriptionRequest build() {
        return createSubscriptionRequest;
    }
}