/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class CreateRegistrationRequestBuilder {
    //the instance to build
    private CreateRegistrationRequest createRegistrationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateRegistrationRequestBuilder() {
        createRegistrationRequest = new CreateRegistrationRequest();
    }

    public CreateRegistrationRequestBuilder description(String description) {
        createRegistrationRequest.setDescription(description);
        return this;
    }

    public CreateRegistrationRequestBuilder dataProvided(DataProvided dataProvided) {
        createRegistrationRequest.setDataProvided(dataProvided);
        return this;
    }

    public CreateRegistrationRequestBuilder provider(Provider1 provider) {
        createRegistrationRequest.setProvider(provider);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateRegistrationRequest build() {
        return createRegistrationRequest;
    }
}