/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateRegistrationRequest type.
 */
public class CreateRegistrationRequest {
    private String description;
    private DataProvided dataProvided;
    private Provider1 provider;

    /**
     * Default constructor.
     */
    public CreateRegistrationRequest() {
    }

    /**
     * Initialization constructor.
     * @param  description  String value for description.
     * @param  dataProvided  DataProvided value for dataProvided.
     * @param  provider  Provider1 value for provider.
     */
    public CreateRegistrationRequest(
            String description,
            DataProvided dataProvided,
            Provider1 provider) {
        this.description = description;
        this.dataProvided = dataProvided;
        this.provider = provider;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for DataProvided.
     * @return Returns the DataProvided
     */
    @JsonGetter("dataProvided")
    public DataProvided getDataProvided() {
        return dataProvided;
    }

    /**
     * Setter for DataProvided.
     * @param dataProvided Value for DataProvided
     */
    @JsonSetter("dataProvided")
    public void setDataProvided(DataProvided dataProvided) {
        this.dataProvided = dataProvided;
    }

    /**
     * Getter for Provider.
     * @return Returns the Provider1
     */
    @JsonGetter("provider")
    public Provider1 getProvider() {
        return provider;
    }

    /**
     * Setter for Provider.
     * @param provider Value for Provider1
     */
    @JsonSetter("provider")
    public void setProvider(Provider1 provider) {
        this.provider = provider;
    }

    /**
     * Converts this CreateRegistrationRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateRegistrationRequest [" + "description=" + description + ", dataProvided="
                + dataProvided + ", provider=" + provider + "]";
    }

    /**
     * Builds a new {@link CreateRegistrationRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateRegistrationRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(description, dataProvided, provider);
        return builder;
    }

    /**
     * Class to build instances of {@link CreateRegistrationRequest}.
     */
    public static class Builder {
        private String description;
        private DataProvided dataProvided;
        private Provider1 provider;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  description  String value for description.
         * @param  dataProvided  DataProvided value for dataProvided.
         * @param  provider  Provider1 value for provider.
         */
        public Builder(String description, DataProvided dataProvided, Provider1 provider) {
            this.description = description;
            this.dataProvided = dataProvided;
            this.provider = provider;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for dataProvided.
         * @param  dataProvided  DataProvided value for dataProvided.
         * @return Builder
         */
        public Builder dataProvided(DataProvided dataProvided) {
            this.dataProvided = dataProvided;
            return this;
        }

        /**
         * Setter for provider.
         * @param  provider  Provider1 value for provider.
         * @return Builder
         */
        public Builder provider(Provider1 provider) {
            this.provider = provider;
            return this;
        }

        /**
         * Builds a new {@link CreateRegistrationRequest} object using the set fields.
         * @return {@link CreateRegistrationRequest}
         */
        public CreateRegistrationRequest build() {
            return new CreateRegistrationRequest(description, dataProvided, provider);
        }
    }
}
