/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Crs2Builder {
    //the instance to build
    private Crs2 crs2;

    /**
     * Default constructor to initialize the instance
     */
    public Crs2Builder() {
        crs2 = new Crs2();
    }

    public Crs2Builder value(String value) {
        crs2.setValue(value);
        return this;
    }

    public Crs2Builder type(String type) {
        crs2.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Crs2 build() {
        return crs2;
    }
}