/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class DataProvidedBuilder {
    //the instance to build
    private DataProvided dataProvided;

    /**
     * Default constructor to initialize the instance
     */
    public DataProvidedBuilder() {
        dataProvided = new DataProvided();
    }

    public DataProvidedBuilder entities(List<Entity> entities) {
        dataProvided.setEntities(entities);
        return this;
    }

    public DataProvidedBuilder attrs(List<String> attrs) {
        dataProvided.setAttrs(attrs);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public DataProvided build() {
        return dataProvided;
    }
}