/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Entity1Builder {
    //the instance to build
    private Entity1 entity1;

    /**
     * Default constructor to initialize the instance
     */
    public Entity1Builder() {
        entity1 = new Entity1();
    }

    public Entity1Builder idPattern(String idPattern) {
        entity1.setIdPattern(idPattern);
        return this;
    }

    public Entity1Builder type(String type) {
        entity1.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Entity1 build() {
        return entity1;
    }
}