/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class FuelBuilder {
    //the instance to build
    private Fuel fuel;

    /**
     * Default constructor to initialize the instance
     */
    public FuelBuilder() {
        fuel = new Fuel();
    }

    public FuelBuilder types(List<String> types) {
        fuel.setTypes(types);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Fuel build() {
        return fuel;
    }
}