/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Headers type.
 */
public class Headers {
    private String xMyHeader;

    /**
     * Default constructor.
     */
    public Headers() {
    }

    /**
     * Initialization constructor.
     * @param  xMyHeader  String value for xMyHeader.
     */
    public Headers(
            String xMyHeader) {
        this.xMyHeader = xMyHeader;
    }

    /**
     * Getter for XMyHeader.
     * @return Returns the String
     */
    @JsonGetter("X-MyHeader")
    public String getXMyHeader() {
        return xMyHeader;
    }

    /**
     * Setter for XMyHeader.
     * @param xMyHeader Value for String
     */
    @JsonSetter("X-MyHeader")
    public void setXMyHeader(String xMyHeader) {
        this.xMyHeader = xMyHeader;
    }

    /**
     * Converts this Headers into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Headers [" + "xMyHeader=" + xMyHeader + "]";
    }

    /**
     * Builds a new {@link Headers.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Headers.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(xMyHeader);
        return builder;
    }

    /**
     * Class to build instances of {@link Headers}.
     */
    public static class Builder {
        private String xMyHeader;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  xMyHeader  String value for xMyHeader.
         */
        public Builder(String xMyHeader) {
            this.xMyHeader = xMyHeader;
        }

        /**
         * Setter for xMyHeader.
         * @param  xMyHeader  String value for xMyHeader.
         * @return Builder
         */
        public Builder xMyHeader(String xMyHeader) {
            this.xMyHeader = xMyHeader;
            return this;
        }

        /**
         * Builds a new {@link Headers} object using the set fields.
         * @return {@link Headers}
         */
        public Headers build() {
            return new Headers(xMyHeader);
        }
    }
}
