/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class HeadersBuilder {
    //the instance to build
    private Headers headers;

    /**
     * Default constructor to initialize the instance
     */
    public HeadersBuilder() {
        headers = new Headers();
    }

    public HeadersBuilder xMyHeader(String xMyHeader) {
        headers.setXMyHeader(xMyHeader);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Headers build() {
        return headers;
    }
}