/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class HttpCustomBuilder {
    //the instance to build
    private HttpCustom httpCustom;

    /**
     * Default constructor to initialize the instance
     */
    public HttpCustomBuilder() {
        httpCustom = new HttpCustom();
    }

    public HttpCustomBuilder url(String url) {
        httpCustom.setUrl(url);
        return this;
    }

    public HttpCustomBuilder headers(Headers headers) {
        httpCustom.setHeaders(headers);
        return this;
    }

    public HttpCustomBuilder qs(Qs qs) {
        httpCustom.setQs(qs);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public HttpCustom build() {
        return httpCustom;
    }
}