/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class HttpCustom 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1247655666686268183L;
    private String url;
    private Headers headers;
    private Qs qs;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("url")
    public String getUrl ( ) { 
        return this.url;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("url")
    public void setUrl (String value) { 
        this.url = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("headers")
    public Headers getHeaders ( ) { 
        return this.headers;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("headers")
    public void setHeaders (Headers value) { 
        this.headers = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("qs")
    public Qs getQs ( ) { 
        return this.qs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("qs")
    public void setQs (Qs value) { 
        this.qs = value;
    }
 
}
