/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Humidity4Builder {
    //the instance to build
    private Humidity4 humidity4;

    /**
     * Default constructor to initialize the instance
     */
    public Humidity4Builder() {
        humidity4 = new Humidity4();
    }

    public Humidity4Builder types(List<String> types) {
        humidity4.setTypes(types);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Humidity4 build() {
        return humidity4;
    }
}