/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ListSubscriptionsResponse type.
 */
public class ListSubscriptionsResponse {
    private String id;
    private String description;
    private Subject subject;
    private Notification notification;
    private String expires;
    private String status;
    private int throttling;

    /**
     * Default constructor.
     */
    public ListSubscriptionsResponse() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  description  String value for description.
     * @param  subject  Subject value for subject.
     * @param  notification  Notification value for notification.
     * @param  expires  String value for expires.
     * @param  status  String value for status.
     * @param  throttling  int value for throttling.
     */
    public ListSubscriptionsResponse(
            String id,
            String description,
            Subject subject,
            Notification notification,
            String expires,
            String status,
            int throttling) {
        this.id = id;
        this.description = description;
        this.subject = subject;
        this.notification = notification;
        this.expires = expires;
        this.status = status;
        this.throttling = throttling;
    }

    /**
     * Getter for Id.
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Description.
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Subject.
     * @return Returns the Subject
     */
    @JsonGetter("subject")
    public Subject getSubject() {
        return subject;
    }

    /**
     * Setter for Subject.
     * @param subject Value for Subject
     */
    @JsonSetter("subject")
    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    /**
     * Getter for Notification.
     * @return Returns the Notification
     */
    @JsonGetter("notification")
    public Notification getNotification() {
        return notification;
    }

    /**
     * Setter for Notification.
     * @param notification Value for Notification
     */
    @JsonSetter("notification")
    public void setNotification(Notification notification) {
        this.notification = notification;
    }

    /**
     * Getter for Expires.
     * @return Returns the String
     */
    @JsonGetter("expires")
    public String getExpires() {
        return expires;
    }

    /**
     * Setter for Expires.
     * @param expires Value for String
     */
    @JsonSetter("expires")
    public void setExpires(String expires) {
        this.expires = expires;
    }

    /**
     * Getter for Status.
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Throttling.
     * @return Returns the int
     */
    @JsonGetter("throttling")
    public int getThrottling() {
        return throttling;
    }

    /**
     * Setter for Throttling.
     * @param throttling Value for int
     */
    @JsonSetter("throttling")
    public void setThrottling(int throttling) {
        this.throttling = throttling;
    }

    /**
     * Converts this ListSubscriptionsResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListSubscriptionsResponse [" + "id=" + id + ", description=" + description
                + ", subject=" + subject + ", notification=" + notification + ", expires=" + expires
                + ", status=" + status + ", throttling=" + throttling + "]";
    }

    /**
     * Builds a new {@link ListSubscriptionsResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListSubscriptionsResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, description, subject, notification, expires, status,
                throttling);
        return builder;
    }

    /**
     * Class to build instances of {@link ListSubscriptionsResponse}.
     */
    public static class Builder {
        private String id;
        private String description;
        private Subject subject;
        private Notification notification;
        private String expires;
        private String status;
        private int throttling;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  description  String value for description.
         * @param  subject  Subject value for subject.
         * @param  notification  Notification value for notification.
         * @param  expires  String value for expires.
         * @param  status  String value for status.
         * @param  throttling  int value for throttling.
         */
        public Builder(String id, String description, Subject subject, Notification notification,
                String expires, String status, int throttling) {
            this.id = id;
            this.description = description;
            this.subject = subject;
            this.notification = notification;
            this.expires = expires;
            this.status = status;
            this.throttling = throttling;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for subject.
         * @param  subject  Subject value for subject.
         * @return Builder
         */
        public Builder subject(Subject subject) {
            this.subject = subject;
            return this;
        }

        /**
         * Setter for notification.
         * @param  notification  Notification value for notification.
         * @return Builder
         */
        public Builder notification(Notification notification) {
            this.notification = notification;
            return this;
        }

        /**
         * Setter for expires.
         * @param  expires  String value for expires.
         * @return Builder
         */
        public Builder expires(String expires) {
            this.expires = expires;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for throttling.
         * @param  throttling  int value for throttling.
         * @return Builder
         */
        public Builder throttling(int throttling) {
            this.throttling = throttling;
            return this;
        }

        /**
         * Builds a new {@link ListSubscriptionsResponse} object using the set fields.
         * @return {@link ListSubscriptionsResponse}
         */
        public ListSubscriptionsResponse build() {
            return new ListSubscriptionsResponse(id, description, subject, notification, expires,
                    status, throttling);
        }
    }
}
