/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ListEntitiesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -5534721061485178813L;
    private String type;
    private String id;
    private Temperature temperature;
    private Speed speed;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("temperature")
    public Temperature getTemperature ( ) { 
        return this.temperature;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("temperature")
    public void setTemperature (Temperature value) { 
        this.temperature = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("speed")
    public Speed getSpeed ( ) { 
        return this.speed;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("speed")
    public void setSpeed (Speed value) { 
        this.speed = value;
    }
 
}
