/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class ListRegistrationsResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 7898252629262494097L;
    private String id;
    private String description;
    private DataProvided dataProvided;
    private Provider provider;
    private String expires;
    private String status;
    private ForwardingInformation forwardingInformation;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("description")
    public String getDescription ( ) { 
        return this.description;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("description")
    public void setDescription (String value) { 
        this.description = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("dataProvided")
    public DataProvided getDataProvided ( ) { 
        return this.dataProvided;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("dataProvided")
    public void setDataProvided (DataProvided value) { 
        this.dataProvided = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("provider")
    public Provider getProvider ( ) { 
        return this.provider;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("provider")
    public void setProvider (Provider value) { 
        this.provider = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expires")
    public String getExpires ( ) { 
        return this.expires;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expires")
    public void setExpires (String value) { 
        this.expires = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public String getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (String value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("forwardingInformation")
    public ForwardingInformation getForwardingInformation ( ) { 
        return this.forwardingInformation;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("forwardingInformation")
    public void setForwardingInformation (ForwardingInformation value) { 
        this.forwardingInformation = value;
    }
 
}
