/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ListEntityTypesResponse type.
 */
public class ListEntityTypesResponse {
    private String type;
    private Attrs attrs;
    private int count;

    /**
     * Default constructor.
     */
    public ListEntityTypesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  attrs  Attrs value for attrs.
     * @param  count  int value for count.
     */
    public ListEntityTypesResponse(
            String type,
            Attrs attrs,
            int count) {
        this.type = type;
        this.attrs = attrs;
        this.count = count;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Attrs.
     * @return Returns the Attrs
     */
    @JsonGetter("attrs")
    public Attrs getAttrs() {
        return attrs;
    }

    /**
     * Setter for Attrs.
     * @param attrs Value for Attrs
     */
    @JsonSetter("attrs")
    public void setAttrs(Attrs attrs) {
        this.attrs = attrs;
    }

    /**
     * Getter for Count.
     * @return Returns the int
     */
    @JsonGetter("count")
    public int getCount() {
        return count;
    }

    /**
     * Setter for Count.
     * @param count Value for int
     */
    @JsonSetter("count")
    public void setCount(int count) {
        this.count = count;
    }

    /**
     * Converts this ListEntityTypesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ListEntityTypesResponse [" + "type=" + type + ", attrs=" + attrs + ", count="
                + count + "]";
    }

    /**
     * Builds a new {@link ListEntityTypesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ListEntityTypesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, attrs, count);
        return builder;
    }

    /**
     * Class to build instances of {@link ListEntityTypesResponse}.
     */
    public static class Builder {
        private String type;
        private Attrs attrs;
        private int count;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  attrs  Attrs value for attrs.
         * @param  count  int value for count.
         */
        public Builder(String type, Attrs attrs, int count) {
            this.type = type;
            this.attrs = attrs;
            this.count = count;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for attrs.
         * @param  attrs  Attrs value for attrs.
         * @return Builder
         */
        public Builder attrs(Attrs attrs) {
            this.attrs = attrs;
            return this;
        }

        /**
         * Setter for count.
         * @param  count  int value for count.
         * @return Builder
         */
        public Builder count(int count) {
            this.count = count;
            return this;
        }

        /**
         * Builds a new {@link ListEntityTypesResponse} object using the set fields.
         * @return {@link ListEntityTypesResponse}
         */
        public ListEntityTypesResponse build() {
            return new ListEntityTypesResponse(type, attrs, count);
        }
    }
}
