/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Metadata5 
        implements java.io.Serializable {
    private static final long serialVersionUID = -133215102738950219L;
    private UnitCode unitCode;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("unitCode")
    public UnitCode getUnitCode ( ) { 
        return this.unitCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("unitCode")
    public void setUnitCode (UnitCode value) { 
        this.unitCode = value;
    }
 
}
