/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Metadata 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3620248405825192427L;
    private Accuracy accuracy;
    private Timestamp timestamp;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accuracy")
    public Accuracy getAccuracy ( ) { 
        return this.accuracy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accuracy")
    public void setAccuracy (Accuracy value) { 
        this.accuracy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("timestamp")
    public Timestamp getTimestamp ( ) { 
        return this.timestamp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("timestamp")
    public void setTimestamp (Timestamp value) { 
        this.timestamp = value;
    }
 
}
