/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Metadata1Builder {
    //the instance to build
    private Metadata1 metadata1;

    /**
     * Default constructor to initialize the instance
     */
    public Metadata1Builder() {
        metadata1 = new Metadata1();
    }

    public Metadata1Builder crs(Crs crs) {
        metadata1.setCrs(crs);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Metadata1 build() {
        return metadata1;
    }
}