/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Metadata1 
        implements java.io.Serializable {
    private static final long serialVersionUID = -133214686099516011L;
    private Crs crs;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("crs")
    public Crs getCrs ( ) { 
        return this.crs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("crs")
    public void setCrs (Crs value) { 
        this.crs = value;
    }
 
}
