/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for NotifyRequest type.
 */
public class NotifyRequest {
    private String subscriptionId;
    private List<Datum> data;

    /**
     * Default constructor.
     */
    public NotifyRequest() {
    }

    /**
     * Initialization constructor.
     * @param  subscriptionId  String value for subscriptionId.
     * @param  data  List of Datum value for data.
     */
    public NotifyRequest(
            String subscriptionId,
            List<Datum> data) {
        this.subscriptionId = subscriptionId;
        this.data = data;
    }

    /**
     * Getter for SubscriptionId.
     * @return Returns the String
     */
    @JsonGetter("subscriptionId")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Setter for SubscriptionId.
     * @param subscriptionId Value for String
     */
    @JsonSetter("subscriptionId")
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for Data.
     * @return Returns the List of Datum
     */
    @JsonGetter("data")
    public List<Datum> getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for List of Datum
     */
    @JsonSetter("data")
    public void setData(List<Datum> data) {
        this.data = data;
    }

    /**
     * Converts this NotifyRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NotifyRequest [" + "subscriptionId=" + subscriptionId + ", data=" + data + "]";
    }

    /**
     * Builds a new {@link NotifyRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NotifyRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(subscriptionId, data);
        return builder;
    }

    /**
     * Class to build instances of {@link NotifyRequest}.
     */
    public static class Builder {
        private String subscriptionId;
        private List<Datum> data;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  subscriptionId  String value for subscriptionId.
         * @param  data  List of Datum value for data.
         */
        public Builder(String subscriptionId, List<Datum> data) {
            this.subscriptionId = subscriptionId;
            this.data = data;
        }

        /**
         * Setter for subscriptionId.
         * @param  subscriptionId  String value for subscriptionId.
         * @return Builder
         */
        public Builder subscriptionId(String subscriptionId) {
            this.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  List of Datum value for data.
         * @return Builder
         */
        public Builder data(List<Datum> data) {
            this.data = data;
            return this;
        }

        /**
         * Builds a new {@link NotifyRequest} object using the set fields.
         * @return {@link NotifyRequest}
         */
        public NotifyRequest build() {
            return new NotifyRequest(subscriptionId, data);
        }
    }
}
