/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Notification1 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1911871882418856669L;
    private Http http;
    private List<String> attrs;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("http")
    public Http getHttp ( ) { 
        return this.http;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("http")
    public void setHttp (Http value) { 
        this.http = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("attrs")
    public List<String> getAttrs ( ) { 
        return this.attrs;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("attrs")
    public void setAttrs (List<String> value) { 
        this.attrs = value;
    }
 
}
