/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Options4Enum to be used.
 */
public enum Options4Enum {
    APPEND,

    KEYVALUES;


    private static TreeMap<String, Options4Enum> valueMap = new TreeMap<>();
    private String value;

    static {
        APPEND.value = "append";
        KEYVALUES.value = "keyValues";

        valueMap.put("append", APPEND);
        valueMap.put("keyValues", KEYVALUES);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static Options4Enum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Options4Enum values to list of string values.
     * @param toConvert The list of Options4Enum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Options4Enum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Options4Enum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 