/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

public enum OptionsEnum {
    COUNT, //TODO: Write general description for this element
    KEYVALUES, //TODO: Write general description for this element
    VALUES, //TODO: Write general description for this element
    UNIQUE; //TODO: Write general description for this element

    private static TreeMap<String, OptionsEnum> valueMap = new TreeMap<String, OptionsEnum>();
    private String value;

    static {
        COUNT.value = "count";
        KEYVALUES.value = "keyValues";
        VALUES.value = "values";
        UNIQUE.value = "unique";

        valueMap.put("count", COUNT);
        valueMap.put("keyValues", KEYVALUES);
        valueMap.put("values", VALUES);
        valueMap.put("unique", UNIQUE);
    }

    /**
     * Returns the enum member associated with the given string value
     * @return The enum member against the given string value */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static OptionsEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member
     * @return The string value against enum member */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of OptionsEnum values to list of string values
     * @param toConvert The list of OptionsEnum values to convert
     * @return List of representative string values */
    public static List<String> toValue(List<OptionsEnum> toConvert) {
        if(toConvert == null)
            return null;
        List<String> convertedValues = new ArrayList<String>();
        for (OptionsEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 