/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class PressureBuilder {
    //the instance to build
    private Pressure pressure;

    /**
     * Default constructor to initialize the instance
     */
    public PressureBuilder() {
        pressure = new Pressure();
    }

    public PressureBuilder types(List<String> types) {
        pressure.setTypes(types);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Pressure build() {
        return pressure;
    }
}