/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Provider1Builder {
    //the instance to build
    private Provider1 provider1;

    /**
     * Default constructor to initialize the instance
     */
    public Provider1Builder() {
        provider1 = new Provider1();
    }

    public Provider1Builder http(Http http) {
        provider1.setHttp(http);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Provider1 build() {
        return provider1;
    }
}