/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Qs 
        implements java.io.Serializable {
    private static final long serialVersionUID = 52521832394642924L;
    private String authToken;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("authToken")
    public String getAuthToken ( ) { 
        return this.authToken;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("authToken")
    public void setAuthToken (String value) { 
        this.authToken = value;
    }
 
}
