/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class QueryResponseBuilder {
    //the instance to build
    private QueryResponse queryResponse;

    /**
     * Default constructor to initialize the instance
     */
    public QueryResponseBuilder() {
        queryResponse = new QueryResponse();
    }

    public QueryResponseBuilder type(String type) {
        queryResponse.setType(type);
        return this;
    }

    public QueryResponseBuilder id(String id) {
        queryResponse.setId(id);
        return this;
    }

    public QueryResponseBuilder temperature(Temperature10 temperature) {
        queryResponse.setTemperature(temperature);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public QueryResponse build() {
        return queryResponse;
    }
}