/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class RetrieveEntityResponseBuilder {
    //the instance to build
    private RetrieveEntityResponse retrieveEntityResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RetrieveEntityResponseBuilder() {
        retrieveEntityResponse = new RetrieveEntityResponse();
    }

    public RetrieveEntityResponseBuilder type(String type) {
        retrieveEntityResponse.setType(type);
        return this;
    }

    public RetrieveEntityResponseBuilder id(String id) {
        retrieveEntityResponse.setId(id);
        return this;
    }

    public RetrieveEntityResponseBuilder temperature(Temperature3 temperature) {
        retrieveEntityResponse.setTemperature(temperature);
        return this;
    }

    public RetrieveEntityResponseBuilder humidity(Humidity2 humidity) {
        retrieveEntityResponse.setHumidity(humidity);
        return this;
    }

    public RetrieveEntityResponseBuilder location(Location2 location) {
        retrieveEntityResponse.setLocation(location);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RetrieveEntityResponse build() {
        return retrieveEntityResponse;
    }
}