/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class RetrieveEntityAttributesResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4007809769332509510L;
    private Temperature3 temperature;
    private Humidity2 humidity;
    private Location2 location;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("temperature")
    public Temperature3 getTemperature ( ) { 
        return this.temperature;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("temperature")
    public void setTemperature (Temperature3 value) { 
        this.temperature = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("humidity")
    public Humidity2 getHumidity ( ) { 
        return this.humidity;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("humidity")
    public void setHumidity (Humidity2 value) { 
        this.humidity = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("location")
    public Location2 getLocation ( ) { 
        return this.location;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("location")
    public void setLocation (Location2 value) { 
        this.location = value;
    }
 
}
