/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class RetrieveEntityTypeResponseBuilder {
    //the instance to build
    private RetrieveEntityTypeResponse retrieveEntityTypeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public RetrieveEntityTypeResponseBuilder() {
        retrieveEntityTypeResponse = new RetrieveEntityTypeResponse();
    }

    public RetrieveEntityTypeResponseBuilder attrs(Attrs1 attrs) {
        retrieveEntityTypeResponse.setAttrs(attrs);
        return this;
    }

    public RetrieveEntityTypeResponseBuilder count(int count) {
        retrieveEntityTypeResponse.setCount(count);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public RetrieveEntityTypeResponse build() {
        return retrieveEntityTypeResponse;
    }
}