/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class SeatNumberBuilder {
    //the instance to build
    private SeatNumber seatNumber;

    /**
     * Default constructor to initialize the instance
     */
    public SeatNumberBuilder() {
        seatNumber = new SeatNumber();
    }

    public SeatNumberBuilder value(int value) {
        seatNumber.setValue(value);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public SeatNumber build() {
        return seatNumber;
    }
}