/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Speed1 type.
 */
public class Speed1 {
    private List<String> types;

    /**
     * Default constructor.
     */
    public Speed1() {
    }

    /**
     * Initialization constructor.
     * @param  types  List of String value for types.
     */
    public Speed1(
            List<String> types) {
        this.types = types;
    }

    /**
     * Getter for Types.
     * @return Returns the List of String
     */
    @JsonGetter("types")
    public List<String> getTypes() {
        return types;
    }

    /**
     * Setter for Types.
     * @param types Value for List of String
     */
    @JsonSetter("types")
    public void setTypes(List<String> types) {
        this.types = types;
    }

    /**
     * Converts this Speed1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Speed1 [" + "types=" + types + "]";
    }

    /**
     * Builds a new {@link Speed1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Speed1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(types);
        return builder;
    }

    /**
     * Class to build instances of {@link Speed1}.
     */
    public static class Builder {
        private List<String> types;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  types  List of String value for types.
         */
        public Builder(List<String> types) {
            this.types = types;
        }

        /**
         * Setter for types.
         * @param  types  List of String value for types.
         * @return Builder
         */
        public Builder types(List<String> types) {
            this.types = types;
            return this;
        }

        /**
         * Builds a new {@link Speed1} object using the set fields.
         * @return {@link Speed1}
         */
        public Speed1 build() {
            return new Speed1(types);
        }
    }
}
