/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Speed1Builder {
    //the instance to build
    private Speed1 speed1;

    /**
     * Default constructor to initialize the instance
     */
    public Speed1Builder() {
        speed1 = new Speed1();
    }

    public Speed1Builder types(List<String> types) {
        speed1.setTypes(types);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Speed1 build() {
        return speed1;
    }
}