/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Speed type.
 */
public class Speed {
    private int value;
    private String type;
    private Metadata metadata;

    /**
     * Default constructor.
     */
    public Speed() {
    }

    /**
     * Initialization constructor.
     * @param  value  int value for value.
     * @param  type  String value for type.
     * @param  metadata  Metadata value for metadata.
     */
    public Speed(
            int value,
            String type,
            Metadata metadata) {
        this.value = value;
        this.type = type;
        this.metadata = metadata;
    }

    /**
     * Getter for Value.
     * @return Returns the int
     */
    @JsonGetter("value")
    public int getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for int
     */
    @JsonSetter("value")
    public void setValue(int value) {
        this.value = value;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Metadata.
     * @return Returns the Metadata
     */
    @JsonGetter("metadata")
    public Metadata getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * @param metadata Value for Metadata
     */
    @JsonSetter("metadata")
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    /**
     * Converts this Speed into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Speed [" + "value=" + value + ", type=" + type + ", metadata=" + metadata + "]";
    }

    /**
     * Builds a new {@link Speed.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Speed.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value, type, metadata);
        return builder;
    }

    /**
     * Class to build instances of {@link Speed}.
     */
    public static class Builder {
        private int value;
        private String type;
        private Metadata metadata;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  int value for value.
         * @param  type  String value for type.
         * @param  metadata  Metadata value for metadata.
         */
        public Builder(int value, String type, Metadata metadata) {
            this.value = value;
            this.type = type;
            this.metadata = metadata;
        }

        /**
         * Setter for value.
         * @param  value  int value for value.
         * @return Builder
         */
        public Builder value(int value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for metadata.
         * @param  metadata  Metadata value for metadata.
         * @return Builder
         */
        public Builder metadata(Metadata metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Builds a new {@link Speed} object using the set fields.
         * @return {@link Speed}
         */
        public Speed build() {
            return new Speed(value, type, metadata);
        }
    }
}
