/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class Temperature3Builder {
    //the instance to build
    private Temperature3 temperature3;

    /**
     * Default constructor to initialize the instance
     */
    public Temperature3Builder() {
        temperature3 = new Temperature3();
    }

    public Temperature3Builder value(double value) {
        temperature3.setValue(value);
        return this;
    }

    public Temperature3Builder type(String type) {
        temperature3.setType(type);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Temperature3 build() {
        return temperature3;
    }
}