/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Temperature10 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3571369073666298259L;
    private double value;
    private String type;
    private Integer accuracy;
    private Timestamp timestamp;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("value")
    public double getValue ( ) { 
        return this.value;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("value")
    public void setValue (double value) { 
        this.value = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("accuracy")
    public Integer getAccuracy ( ) { 
        return this.accuracy;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("accuracy")
    public void setAccuracy (Integer value) { 
        this.accuracy = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("timestamp")
    public Timestamp getTimestamp ( ) { 
        return this.timestamp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("timestamp")
    public void setTimestamp (Timestamp value) { 
        this.timestamp = value;
    }
 
}
