/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Temperature7 
        implements java.io.Serializable {
    private static final long serialVersionUID = -2085523012961923L;
    private List<String> types;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("types")
    public List<String> getTypes ( ) { 
        return this.types;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("types")
    public void setTypes (List<String> value) { 
        this.types = value;
    }
 
}
