/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Timestamp type.
 */
public class Timestamp {
    private String value;
    private String type;

    /**
     * Default constructor.
     */
    public Timestamp() {
    }

    /**
     * Initialization constructor.
     * @param  value  String value for value.
     * @param  type  String value for type.
     */
    public Timestamp(
            String value,
            String type) {
        this.value = value;
        this.type = type;
    }

    /**
     * Getter for Value.
     * @return Returns the String
     */
    @JsonGetter("value")
    public String getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for String
     */
    @JsonSetter("value")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Converts this Timestamp into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Timestamp [" + "value=" + value + ", type=" + type + "]";
    }

    /**
     * Builds a new {@link Timestamp.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Timestamp.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(value, type);
        return builder;
    }

    /**
     * Class to build instances of {@link Timestamp}.
     */
    public static class Builder {
        private String value;
        private String type;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  value  String value for value.
         * @param  type  String value for type.
         */
        public Builder(String value, String type) {
            this.value = value;
            this.type = type;
        }

        /**
         * Setter for value.
         * @param  value  String value for value.
         * @return Builder
         */
        public Builder value(String value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link Timestamp} object using the set fields.
         * @return {@link Timestamp}
         */
        public Timestamp build() {
            return new Timestamp(value, type);
        }
    }
}
