/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class UpdateRegistrationRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 132632718343659497L;
    private String expires;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("expires")
    public String getExpires ( ) { 
        return this.expires;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("expires")
    public void setExpires (String value) { 
        this.expires = value;
    }
 
}
