/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class UpdateRegistrationRequestBuilder {
    //the instance to build
    private UpdateRegistrationRequest updateRegistrationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateRegistrationRequestBuilder() {
        updateRegistrationRequest = new UpdateRegistrationRequest();
    }

    public UpdateRegistrationRequestBuilder expires(String expires) {
        updateRegistrationRequest.setExpires(expires);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateRegistrationRequest build() {
        return updateRegistrationRequest;
    }
}