/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion.models;

import java.util.*;

public class UpdateSubscriptionRequestBuilder {
    //the instance to build
    private UpdateSubscriptionRequest updateSubscriptionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public UpdateSubscriptionRequestBuilder() {
        updateSubscriptionRequest = new UpdateSubscriptionRequest();
    }

    public UpdateSubscriptionRequestBuilder expires(String expires) {
        updateSubscriptionRequest.setExpires(expires);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public UpdateSubscriptionRequest build() {
        return updateSubscriptionRequest;
    }
}