/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UpdateRequest type.
 */
public class UpdateRequest {
    private String actionType;
    private List<Entity5> entities;

    /**
     * Default constructor.
     */
    public UpdateRequest() {
    }

    /**
     * Initialization constructor.
     * @param  actionType  String value for actionType.
     * @param  entities  List of Entity5 value for entities.
     */
    public UpdateRequest(
            String actionType,
            List<Entity5> entities) {
        this.actionType = actionType;
        this.entities = entities;
    }

    /**
     * Getter for ActionType.
     * @return Returns the String
     */
    @JsonGetter("actionType")
    public String getActionType() {
        return actionType;
    }

    /**
     * Setter for ActionType.
     * @param actionType Value for String
     */
    @JsonSetter("actionType")
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    /**
     * Getter for Entities.
     * @return Returns the List of Entity5
     */
    @JsonGetter("entities")
    public List<Entity5> getEntities() {
        return entities;
    }

    /**
     * Setter for Entities.
     * @param entities Value for List of Entity5
     */
    @JsonSetter("entities")
    public void setEntities(List<Entity5> entities) {
        this.entities = entities;
    }

    /**
     * Converts this UpdateRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateRequest [" + "actionType=" + actionType + ", entities=" + entities + "]";
    }

    /**
     * Builds a new {@link UpdateRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(actionType, entities);
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateRequest}.
     */
    public static class Builder {
        private String actionType;
        private List<Entity5> entities;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  actionType  String value for actionType.
         * @param  entities  List of Entity5 value for entities.
         */
        public Builder(String actionType, List<Entity5> entities) {
            this.actionType = actionType;
            this.entities = entities;
        }

        /**
         * Setter for actionType.
         * @param  actionType  String value for actionType.
         * @return Builder
         */
        public Builder actionType(String actionType) {
            this.actionType = actionType;
            return this;
        }

        /**
         * Setter for entities.
         * @param  entities  List of Entity5 value for entities.
         * @return Builder
         */
        public Builder entities(List<Entity5> entities) {
            this.entities = entities;
            return this;
        }

        /**
         * Builds a new {@link UpdateRequest} object using the set fields.
         * @return {@link UpdateRequest}
         */
        public UpdateRequest build() {
            return new UpdateRequest(actionType, entities);
        }
    }
}
