/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package org.fiware.lab.orion.controllers;

import java.io.IOException;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import org.fiware.lab.orion.ApiHelper;
import org.fiware.lab.orion.AuthManager;
import org.fiware.lab.orion.Configuration;
import org.fiware.lab.orion.exceptions.ApiException;
import org.fiware.lab.orion.http.Headers;
import org.fiware.lab.orion.http.client.HttpCallback;
import org.fiware.lab.orion.http.client.HttpClient;
import org.fiware.lab.orion.http.client.HttpContext;
import org.fiware.lab.orion.http.request.HttpRequest;
import org.fiware.lab.orion.http.response.HttpResponse;
import org.fiware.lab.orion.http.response.HttpStringResponse;
import org.fiware.lab.orion.models.RetrieveAPIResourcesResponse;

/**
 * This class lists all the endpoints of the groups.
 */
public final class APIEntryPointController extends BaseController {

    /**
     * Initializes the controller.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     */
    public APIEntryPointController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers) {
        super(config, httpClient, authManagers);
    }

    /**
     * Initializes the controller with HTTPCallback.
     * @param config    Configurations added in client.
     * @param httpClient    Send HTTP requests and read the responses.
     * @param authManagers    Apply authorization to requests.
     * @param httpCallback    Callback to be called before and after the HTTP call.
     */
    public APIEntryPointController(Configuration config, HttpClient httpClient,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        super(config, httpClient, authManagers, httpCallback);
    }

    /**
     * This resource does not have any attributes. Instead it offers the initial API affordances in
     * the form of the links in the JSON body. It is recommended to follow the “url” link values,
     * [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve
     * resources. Instead of constructing your own URLs, to keep your client decoupled from
     * implementation details.
     * @return    Returns the RetrieveAPIResourcesResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public RetrieveAPIResourcesResponse retrieveAPIResources() throws ApiException, IOException {
        HttpRequest request = buildRetrieveAPIResourcesRequest();
        HttpResponse response = getClientInstance().execute(request, false);
        HttpContext context = new HttpContext(request, response);

        return handleRetrieveAPIResourcesResponse(context);
    }

    /**
     * This resource does not have any attributes. Instead it offers the initial API affordances in
     * the form of the links in the JSON body. It is recommended to follow the “url” link values,
     * [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve
     * resources. Instead of constructing your own URLs, to keep your client decoupled from
     * implementation details.
     * @return    Returns the RetrieveAPIResourcesResponse response from the API call
     */
    public CompletableFuture<RetrieveAPIResourcesResponse> retrieveAPIResourcesAsync() {
        return makeHttpCallAsync(() -> buildRetrieveAPIResourcesRequest(),
            request -> getClientInstance().executeAsync(request, false),
            context -> handleRetrieveAPIResourcesResponse(context));
    }

    /**
     * Builds the HttpRequest object for retrieveAPIResources.
     */
    private HttpRequest buildRetrieveAPIResourcesRequest() {
        //the base uri for api requests
        String baseUri = config.getBaseUri();

        //prepare query string for API call
        final StringBuilder queryBuilder = new StringBuilder(baseUri
                + "/v2");

        //load all headers for the outgoing API request
        Headers headers = new Headers();
        headers.add("user-agent", BaseController.userAgent);
        headers.add("accept", "application/json");

        //prepare and invoke the API call request to fetch the response
        HttpRequest request = getClientInstance().get(queryBuilder, headers, null, null);

        // Invoke the callback before request if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onBeforeRequest(request);
        }

        return request;
    }

    /**
     * Processes the response for retrieveAPIResources.
     * @return An object of type RetrieveAPIResourcesResponse
     */
    private RetrieveAPIResourcesResponse handleRetrieveAPIResourcesResponse(
            HttpContext context) throws ApiException, IOException {
        HttpResponse response = context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallback() != null) {
            getHttpCallback().onAfterResponse(context);
        }

        //handle errors defined at the API level
        validateResponse(response, context);

        //extract result from the http response
        String responseBody = ((HttpStringResponse) response).getBody();
        RetrieveAPIResourcesResponse result = ApiHelper.deserialize(responseBody,
                RetrieveAPIResourcesResponse.class);

        return result;
    }

}