/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://orion.lab.fiware.org";

}
