/*
 * FIWARENGSIV2SpecificationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package org.fiware.lab.orion;

import org.fiware.lab.orion.controllers.*;
import org.fiware.lab.orion.http.client.HttpClient;

public class FIWARENGSIV2SpecificationClient {
    /**
     * Singleton access to APIEntryPoint controller
     * @return	Returns the APIEntryPointController instance 
     */
    public APIEntryPointController getAPIEntryPoint() {
        return APIEntryPointController.getInstance();
    }

    /**
     * Singleton access to Entities controller
     * @return	Returns the EntitiesController instance 
     */
    public EntitiesController getEntities() {
        return EntitiesController.getInstance();
    }

    /**
     * Singleton access to Attributes controller
     * @return	Returns the AttributesController instance 
     */
    public AttributesController getAttributes() {
        return AttributesController.getInstance();
    }

    /**
     * Singleton access to AttributeValue controller
     * @return	Returns the AttributeValueController instance 
     */
    public AttributeValueController getAttributeValue() {
        return AttributeValueController.getInstance();
    }

    /**
     * Singleton access to Types controller
     * @return	Returns the TypesController instance 
     */
    public TypesController getTypes() {
        return TypesController.getInstance();
    }

    /**
     * Singleton access to Subscriptions controller
     * @return	Returns the SubscriptionsController instance 
     */
    public SubscriptionsController getSubscriptions() {
        return SubscriptionsController.getInstance();
    }

    /**
     * Singleton access to Registrations controller
     * @return	Returns the RegistrationsController instance 
     */
    public RegistrationsController getRegistrations() {
        return RegistrationsController.getInstance();
    }

    /**
     * Singleton access to BatchOperations controller
     * @return	Returns the BatchOperationsController instance 
     */
    public BatchOperationsController getBatchOperations() {
        return BatchOperationsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public FIWARENGSIV2SpecificationClient() {
    }

}